# Generated by Django 3.1.6 on 2021-06-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='postID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
