# Generated by Django 3.2.4 on 2021-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userAvatar',
            field=models.ImageField(blank=True, upload_to='userPics/'),
        ),
    ]
