# Generated by Django 3.2.4 on 2021-06-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0003_rename_useravatar_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
