# Generated by Django 3.1.6 on 2021-06-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
