# Generated by Django 3.1.6 on 2021-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0004_auto_20210609_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
