# Generated by Django 3.2.4 on 2021-06-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainWebsite', '0007_alter_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
